#grocery=["cars","lolipop","deo","soap",56]
#print(grocery[0])
#numbers=[2,6,6]
#print(numbers[2])
#numbers.sort()
#numbers.reverse()
#print(numbers[0:3])
#numbers.append(69)
#numbers.insert(1,6)
#print(numbers)
#numbers[1]=88
#print(numbers)
#tp=(1,2,3,)
#print(tp)
a=1
b=2
print(a,b)